name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "staging" ]; then
            echo "Pull requests to main branch (production) are only allowed from staging branch. Change source branch to staging."
            exit 1
          fi
