name: Deploy Test
run-name: "Deploy to ${{ github.ref == 'refs/heads/staging' && 'Staging' || 'Production' }}"
on:
  # push:
  #   branches:
  #     - staging

  pull_request:
    branches:
      - staging
      - main
    types:
      - closed

jobs:
  deploy:
    name: Build Theme and Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'refs/heads/staging' && 'Staging' || 'Production' }}
    steps:
      - name: Echo
        run: |
          pwd
          ls -a
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub base ref: ${{ github.base_ref }}"
          echo "GitHub event pull request base ref: ${{github.event.pull_request.base.ref}}"
          echo "GitHub event name: ${{github.event_name}}"
