name: FusionAuth Deployment

on: push

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: FusionAuth/fusionauth-theme-helper
          ref: 195b41772db95eb082853ea3211950e8c44d5397  # specific commit hash to ensure consistency
      
      - name: Create 'tmp' directory for theme files
        run: mkdir tmp

      - name: Checkout fusionauth-appsembler-theme
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: tmp

      - name: Add environmental variables
        run: |
          cat << EOF > .env

          API_KEY=${{ env.API_KEY }}
          THEME_ID=${{ env.THEME_ID }}
          FUSIONAUTH_URL=${{ env.FUSIONAUTH_URL }}
          TMP_DIR=tmp

          EOF

      - name: Display copied files
        run: |
          echo "$env.API_KEY"
          pwd
          ls -a
          echo '**************'
          ls -a tmp
          echo '--FINISHED--'
          cat .env
