name: FusionAuth Staging Deployment

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fusionauth-theme-helper repository
        uses: actions/checkout@v4
        with:
          repository: FusionAuth/fusionauth-theme-helper
          ref: 195b41772db95eb082853ea3211950e8c44d5397  # specific commit hash to ensure consistency

      - name: Create 'tmp' directory for theme files
        run: mkdir tmp

      - name: Checkout fusionauth-appsembler-theme
        uses: actions/checkout@v4
        with:
          repository: jfaMan/fusionauth-theme-files-backup # original = ${{ "github.repository
          token: ${{ vars.MY_PAT }}
          path: tmp

      - name: Add environment variables
        run: |
          cat << EOF > .env

          API_KEY=${{ vars.STAGING_API_KEY }}
          THEME_ID=${{ vars.STAGING_THEME_ID }}
          FUSIONAUTH_URL=${{ vars.STAGING_FUSIONAUTH_URL }}
          TMP_DIR=tmp

          EOF

      - name: Add Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run NPM
        run: npm install

      - name: Check Node version
        run: node -v

      - name: Run FusionAuth Theme Helper and upload theme files to FusionAuth staging
        run: ./upload.sh