name: FusionAuth Deployment

on: push

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: FusionAuth/fusionauth-theme-helper
          ref: 195b41772db95eb082853ea3211950e8c44d5397  # specific commit hash to ensure consistency
      
      - name: Create 'tmp' directory for theme files
        run: mkdir tmp

      - name: Checkout fusionauth-appsembler-theme
        uses: actions/checkout@v4
        with:
          repository: jfaMan/fusionauth-theme-files-backup # original = ${{ "github.repository
          token: ${{ vars.MY_PAT }}
          path: tmp

      - name: Add environmental variables
        run: |
          cat << EOF > .env

          API_KEY=${{ vars.API_KEY }}
          THEME_ID=${{ vars.THEME_ID }}
          FUSIONAUTH_URL=${{ vars.FUSIONAUTH_URL }}
          TMP_DIR=tmp

          EOF

      - name: Add Node JS v20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Run NPM
        run: npm install

      - name: Display copied files
        run: |
          pwd
          ls -a
          echo '**************'
          ls -a tmp
          echo '--FINISHED--'
          cat .env

      - name: Run FusionAuth Theme Helper and upload theme files to FusionAuth staging
        run: ./upload.sh