name: Push Workflow

on: push

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: FusionAuth/fusionauth-theme-helper
          ref: 195b41772db95eb082853ea3211950e8c44d5397  # specific commit hash to ensure consistency

      - name: Display copied files
        run: |
          pwd
          ls -a  # Display copied files (optional)
          echo 'hello'
          echo 'bye'