name: Create main -> prod pull request on main push
on:
  push:
    branches:
      - main

jobs:
  main-prod-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "main"
          PULL_REQUEST_BRANCH: "prod"
          PULL_REQUEST_TITLE: "`main` (staging) -> `prod` (production)"
          PULL_REQUEST_BODY: |
            This is an automated pull request from branch `main` (staging) into `prod` (production).
            Please review the changes.
