name: Create staging -> main pull request on staging push
on:
  push:
    branches:
      - staging

jobs:
  prod-deployment-pr:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "staging"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_TITLE: "`staging` -> `main` (production)"
          PULL_REQUEST_BODY: |
            This is an automated pull request from branch `staging` into `main` (production).
            Please review the changes.
